TARGET = xp-skc-l2-single
APP_NAME =
XCC_FLAGS = -O2 -g -DSMI_MDC_BIT=1 -DSMI_MDIO_BIT=0
USED_MODULES = module_ethercat module_ethernet_smi module_slicekit_xn

#=============================================================================
# The following part of the Makefile includes the common build infrastructure
# for compiling XMOS applications. You should not need to edit below here.

XMOS_MAKE_PATH ?= ../..
include $(XMOS_MAKE_PATH)/xcommon/module_xcommon/build/Makefile.common
